config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get 'hello', to: "examples#hello" 

	# If you want to route /articles (without the prefix /admin) to Admin::ArticlesController, you could use:
	# scope module: 'admin' do
	#	  resources :articles, :comments
	# end

	# If you want to route /admin/articles to ArticlesController (without the Admin:: module prefix), you could use:
	# scope '/admin' do
	#	  resources :articles, :comments
	# end

	# If you want both!
	# namespace :admin do
	#	  resources :articles, :comments
	# end
	
	@told = false

	def single_pages(n)
		# The namespace's index page
		get n, to: n.to_s+'/single_pages#index', as: n.to_s+'_index'
		namespace n do
			# Record routes to SinglePages controller
			# resources :records
			if ActiveRecord::Base.connection.data_source_exists? 'records'

				# Page for playing around with records
				get 'playground', to: 'single_pages#playground'
				recs = Record.where(set: 'Playground')
				recs.each do |rec|
					action = rec.table_name
					scope '/playground' do
						get action, to: "single_pages##{action}", as: "playground_#{action}"
					end
				end

				# The knowledge base 
				get 'knowledgebase', to: 'single_pages#knowledgebase'
				recs = Record.where(set: 'Funfair')
				recs.each do |rec|
					action = rec.table_name
					scope '/knowledgebase' do
						get action, to: "single_pages##{action}", as: "kb_#{action}"
					end
				end

			else
				if not @told
					# STDERR.puts "ENV['RAILS_ENV']: #{ENV['RAILS_ENV']} – You may need to add `records'"
					STDERR.puts "Rails.env: #{Rails.env} – You may need to add `records'"
					@told = true
				end
			end

			# The home page
			get 'home', to: 'single_pages#the_home'
			# The catalogue page
			get 'catalogue', to: 'single_pages#catalogue'
			# The about page
			get 'about', to: 'single_pages#about'
			# The contact page
			get 'contact', to: 'single_pages#contact'
			# The settings page
			get 'settings', to: 'single_pages#settings'
			# The routes page
			get 'routes', to: 'single_pages#routes'
			# The timeline page
			get 'timeline', to: 'single_pages#timeline'
			# The raw data page
			get 'raw_data', to: 'single_pages#raw_data'
			# The publications page
			get 'publications', to: 'single_pages#publications'
			resources :single_pages, only: [] do
				collection do
					# get 'publications'
				end
			end
		end
	end

	single_pages(:the_app)

	single_pages(:each)

	# Namespace and version the api

	namespace :api do
		# zotero models (or windows onto them)
		resources :q_authors
		resources :q_digital_philosophies
		resources :q_critical_writings
		resources :records

		# super duper abstract model (?)
		resources :entities
		resources :works
		resources :types

		# tables for experimenting with
  	resources :foos
  	resources :goos
	end

end

app/models/api.rb
module Api
  def self.table_name_prefix
    'api_'
  end
end

app/models/author.rb
class Author < Wikidatum
	has_many :authors_of, class_name: "AuthorOf"
	has_many :works, through: :authors_of
end

app/models/author_of.rb
class AuthorOf < ApplicationRecord
 	self.primary_keys = :author_id,:of_id
end

app/models/dummy.rb
class Dummy < ApplicationRecord
end

app/models/entity.rb
class Entity < ApplicationRecord

	def self.link_name
		'part_id'
	end

	# recursive relationship association defintions
	belongs_to :part_of, class_name: 'Entity', foreign_key: link_name, optional: true
	has_many   :parts,   class_name: 'Entity', foreign_key: link_name

	# type relationship association definition
	belongs_to :type

	require 'recursive_sql'
	include RecursiveSQL::InstanceMethods
	extend RecursiveSQL::ClassMethods

end

app/models/foo.rb
class Foo < ApplicationRecord
end

app/models/genre.rb
class Genre < Wikidatum
	has_many :genres_of, class_name: "GenreOf"
	has_many :works, through: :genres_of
end

app/models/genre_of.rb
class GenreOf < ApplicationRecord # naming is hard :(
 	self.primary_keys = :genre_id,:of_id

	belongs_to :genre, primary_key: :q #foreign_key: :genre_id
	# :of_id should be :work_id ?
	belongs_to :work,  primary_key: :q, foreign_key: :of_id
end

app/models/goo.rb
class Goo < ApplicationRecord
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :image, polymorphic: true
end

app/models/q.rb
module Q
  def self.table_name_prefix
    'q_'
  end
end

app/models/record.rb
class Record < ApplicationRecord
end

app/models/schema.rb
class Schema < ApplicationRecord
end

app/models/type.rb
class Type < ApplicationRecord

	def self.link_name
		'supertype_id'
	end

	# don't give an association name the same name as an attribute, no good can come of it
	belongs_to :supertype, class_name: 'Type', optional: true # Top has no ancestor
	has_many   :subtypes,  class_name: 'Type', foreign_key: link_name

	# typing relation
	has_many   :instances, class_name: 'Entity', foreign_key: 'type_id'

	require 'recursive_sql'
	include RecursiveSQL::InstanceMethods
	extend RecursiveSQL::ClassMethods

end

app/models/what.rb
class What < Wikidatum
end

app/models/what_of.rb
class WhatOf < ApplicationRecord
 	self.primary_keys = :what_id,:of_id
end

app/models/wikidatum.rb
class Wikidatum < ApplicationRecord
	self.primary_key = 'q'
end

app/models/work.rb
# class Work < ApplicationRecord
# 	self.primary_key = 'item'
# end

class Work < Wikidatum
	def self.only_genre
		self.where(q: GenreOf.pluck(:of_id).uniq)
	end
	has_many :genres_of, class_name: "GenreOf"
	has_many :genres, through: :genres_of
	def self.only_author
		self.where(q: AuthorOf.pluck(:of_id).uniq)
	end
	has_many :authors_of, class_name: "AuthorOf"
	has_many :authors, through: :authors_of
end

app/models/work_ext.rb
class WorkExt < ApplicationRecord
  # belongs_to :wikidatum
end

app/controllers/api/foos_controller.rb
class Api::FoosController < ApplicationController
  before_action :set_foo, only: [:show, :update, :destroy]

  # GET /foos
  def index
    @foos = Foo.all

    render json: @foos
  end

  # GET /foos/1
  def show
    render json: @foo
  end

  # POST /foos
  def create
    @foo = Foo.new(foo_params)

    if @foo.save
      render json: @foo, status: :created, location: "/api/foos/#{@foo.id}" # what's the best way to do this?
    else
      render json: @foo.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /foos/1
  def update
    if @foo.update(foo_params)
      render json: @foo
    else
      render json: @foo.errors, status: :unprocessable_entity
    end
  end

  # DELETE /foos/1
  def destroy
    @foo.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foo
      @foo = Foo.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def foo_params
      params.require(:foo).permit(:bar, :baz, :bam)
    end
end

app/helpers/foos_helper.rb
module FoosHelper
end

app/helpers/goos_helper.rb
module GoosHelper
end

app/helpers/records_helper.rb
module RecordsHelper
	def records_path(rec)
		''
	end
end

app/views/foos/_form.html.erb
<%= form_with(model: foo, local: true) do |form| %>
  <% if foo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(foo.errors.count, "error") %> prohibited this foo from being saved:</h2>

      <ul>
      <% foo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :bam %>
    <%= form.date_select :bam %>
  </div>

  <div class="field">
    <%= form.label :baz %>
    <%= form.text_field :baz %>
  </div>

  <div class="field">
    <%= form.label :bar %>
    <%= form.number_field :bar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/foos/edit.html.erb
<h1>Editing Foo</h1>

<%= render 'form', foo: @foo %>

<%= link_to 'Show', @foo %> |
<%= link_to 'Back', foos_path %>

app/views/foos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Foos</h1>

<table>
  <thead>
    <tr>
      <th>Bam</th>
      <th>Baz</th>
      <th>Bar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foos.each do |foo| %>
      <tr>
        <td><%= foo.bam %></td>
        <td><%= foo.baz %></td>
        <td><%= foo.bar %></td>
        <td><%= link_to 'Show', foo %></td>
        <td><%= link_to 'Edit', edit_foo_path(foo) %></td>
        <td><%= link_to 'Destroy', foo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Foo', new_foo_path %>

app/views/foos/new.html.erb
<h1>New Foo</h1>

<%= render 'form', foo: @foo %>

<%= link_to 'Back', foos_path %>

app/views/foos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bam:</strong>
  <%= @foo.bam %>
</p>

<p>
  <strong>Baz:</strong>
  <%= @foo.baz %>
</p>

<p>
  <strong>Bar:</strong>
  <%= @foo.bar %>
</p>

<%= link_to 'Edit', edit_foo_path(@foo) %> |
<%= link_to 'Back', foos_path %>