config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get 'hello', to: "examples#hello" 

	# If you want to route /articles (without the prefix /admin) to Admin::ArticlesController, you could use:
	# scope module: 'admin' do
	#	  resources :articles, :comments
	# end

	# If you want to route /admin/articles to ArticlesController (without the Admin:: module prefix), you could use:
	# scope '/admin' do
	#	  resources :articles, :comments
	# end

	# If you want both!
	# namespace :admin do
	#	  resources :articles, :comments
	# end
	
	@told = false

	def single_pages(n)
		# The namespace's index page
		get n, to: n.to_s+'/single_pages#index', as: n.to_s+'_index'
		namespace n do
			# Record routes to SinglePages controller
			# resources :records
			if ActiveRecord::Base.connection.data_source_exists? 'records'

				# Page for playing around with records
				get 'playground', to: 'single_pages#playground'
				recs = Record.where(set: 'Playground')
				recs.each do |rec|
					action = rec.table_name
					scope '/playground' do
						get action, to: "single_pages##{action}", as: "playground_#{action}"
					end
				end

				# The knowledge base 
				get 'knowledgebase', to: 'single_pages#knowledgebase'
				recs = Record.where(set: 'Funfair')
				recs.each do |rec|
					action = rec.table_name
					scope '/knowledgebase' do
						get action, to: "single_pages##{action}", as: "kb_#{action}"
					end
				end

			else
				if not @told
					# STDERR.puts "ENV['RAILS_ENV']: #{ENV['RAILS_ENV']} – You may need to add `records'"
					STDERR.puts "Rails.env: #{Rails.env} – You may need to add `records'"
					@told = true
				end
			end

			# The home page
			get 'home', to: 'single_pages#the_home'
			# The catalogue page
			get 'catalogue', to: 'single_pages#catalogue'
			# The about page
			get 'about', to: 'single_pages#about'
			# The contact page
			get 'contact', to: 'single_pages#contact'
			# The settings page
			get 'settings', to: 'single_pages#settings'
			# The routes page
			get 'routes', to: 'single_pages#routes'
			# The timeline page
			get 'timeline', to: 'single_pages#timeline'
			# The raw data page
			get 'raw_data', to: 'single_pages#raw_data'
			# The publications page
			get 'publications', to: 'single_pages#publications'
			resources :single_pages, only: [] do
				collection do
					# get 'publications'
				end
			end
		end
	end

	single_pages(:the_app)

	single_pages(:each)

	# Namespace and version the api

	namespace :api do
		# zotero models (or windows onto them)
		resources :q_authors
		resources :q_digital_philosophies
		resources :q_critical_writings
		resources :records

		# super duper abstract model (?)
		resources :entities
		resources :works
		resources :types

		# tables for experimenting with
  	resources :foos
  	resources :goos
	end

end

app/controllers/each/single_pages_controller.rb
class Each::SinglePagesController < BaseController
  before_action :set_layout

	def index
	end

	# helper_method :record_attributes

	def record_attributes(table)
		record_name = table.to_s
		record_attr_names = table.attribute_names - [table.primary_key, "created_at", "updated_at"]
		record_attr_types = {}
		record_defaults = {}
		record_nulls = {}
		ruby_to_html5input = {
			:date => "date",
			:integer => "number",
			:string => "text"
		}
		record_attr_names.each do |v|
			record_attr_types[v] = ruby_to_html5input[table.columns_hash[v].type]
			record_defaults[v] = table.columns_hash[v].default
			record_nulls[v] = table.columns_hash[v].null
		end
		return [record_name, record_attr_names, record_attr_types, record_defaults, record_nulls]
	end

	def many_records
		@mr = [] # many records
		@mr[0] = {}
		@mr[0][:name], @mr[0][:attr_names], @mr[0][:attr_types], @mr[0][:defaults], @mr[0][:nulls] = record_attributes(Foo)
		@mr[1] = {}
		@mr[1][:name], @mr[1][:attr_names], @mr[1][:attr_types], @mr[1][:defaults], @mr[1][:nulls] = record_attributes(Goo)
	end

	def foos
		@record_name, @record_attr_names, @record_attr_types, @record_defaults, @record_nulls = record_attributes(Foo)
		# helpers.record_attributes
		render :record
	end

	def goos
		@record_name, @record_attr_names, @record_attr_types, @record_defaults, @record_nulls = record_attributes(Goo)
		# helpers.record_attributes
		render :record
	end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_layout
     	@layout = "each"
    end

    # Only allow a trusted parameter "white list" through.
    def single_page_params
      params.require(:record).permit(:layout)
    end
end

app/controllers/the_app/single_pages_controller.rb
class TheApp::SinglePagesController < BaseController
  before_action :set_layout

	def index
	end

	# helper_method :record_attributes
	
	require 'record_helper'

	def record_attributes(model)
		table_name = mdl2tbl(model)
		record_name = model.to_s
		record_attr_names = model.attribute_names - [model.primary_key, "created_at", "updated_at"]
		record_attr_types = {}
		record_defaults = {}
		record_nulls = {}
		ruby_to_html5input = {
			:date => "date",
			:integer => "number",
			:string => "text"
		}
		# Rails.logger.info model.columns_hash
		record_attr_names.each do |v|
			# Rails.logger.warn "===> #{v.inspect}"
			record_attr_types[v] = ruby_to_html5input[model.columns_hash[v].type]
			record_defaults[v] = model.columns_hash[v].default
			record_nulls[v] = model.columns_hash[v].null
		end
		r = {}
		r[:record_name],r[:attr_names],r[:attr_types],r[:defaults],r[:nulls],r[:table_name]=[record_name,record_attr_names,record_attr_types,record_defaults,record_nulls,table_name]
		r
	end

	#

	def a_record(rec_const)
		@record_name, @record_attr_names, @record_attr_types, @record_defaults, @record_nulls, @table_name = record_attributes(rec_const).values
	end

	# dynamically generate these

	def foos
		a_record(Foo) # writeable defaults to true?!
		render :record
	end

	def goos
		a_record(Goo) # writeable defaults to true?!
		render :record
	end

	def foos_n_goos
		@mr = [] # many records
		@mr[0] = record_attributes(Foo)
		@mr[1] = record_attributes(Goo)
		render 'many_records'
	end

	# the playground
	
	def records
		a_record(Record)
		render :record
	end

	def playground
		@mr = [] # many records
		@mr[0] = {}
		@mr[0][:record_name], @mr[0][:attr_names], @mr[0][:attr_types], @mr[0][:defaults], @mr[0][:nulls], @mr[0][:table_name] = record_attributes(Record)
		render 'many_records'
	end

	# the kb (automate!)

	def q_authors
		respond_to do |format|
			format.html do
				a_record(Q::Author)
				@writeable = false
				render :record
			end
			format.json { redirect_to api_q_authors_url }
		end
	end

	def q_digital_philosophies
		respond_to do |format|
			format.html do
				a_record(Q::DigitalPhilosophy)
				@writeable = false
				render :record
			end
			format.json { redirect_to api_q_authors_url }
		end
	end

	def q_critical_writings
		respond_to do |format|
			format.html do
				a_record(Q::CriticalWriting)
				@writeable = false
				render :record
			end
			format.json { redirect_to api_q_authors_url }
		end
	end

	def knowledgebase
		@mr = []
		@mr[0] = record_attributes(Q::DigitalPhilosophy)
		@mr[1] = record_attributes(Q::CriticalWriting)
		@mr[2] = record_attributes(Q::Author)
		render 'many_records'
	end

	#

	def the_home
	end

	def about
	end

	INITIAL_SEGMENT_REGEX = %r{^\/([^\/\(:]+)}
	APP_ROOT = Rails.configuration.x.the_app.app_root
	APP_SEGMENT_REGEX = /^\/#{APP_ROOT}(.*)\(.+/

	# https://gist.github.com/bantic/5688232
	# “Programmatically list all routes (/paths) from within a rails app.”

	def match_initial_path_segment(path)
		if match = APP_SEGMENT_REGEX.match(path)
			Rails.logger.info match.inspect
			match[1]
		end
	end

	RAW_DATA_DIR = Rails.configuration.x.zotero.raw_data_dir
	WORKS = Rails.configuration.x.zotero.the_works

	def raw_data
		fl = Dir.glob(RAW_DATA_DIR+"/*"+WORKS)
		fn = fl.sort.last
		@raw_data = File.read(fn)
	end

	def routes
		routes = Rails.application.routes.routes
    paths = routes.collect {|r| r.path.spec.to_s }
		Rails.logger.info paths
		@initial_path_segments ||= begin
			paths.collect {|path|
				match_initial_path_segment(path)
			}.compact.uniq
		end
	end

	def index
		redirect_to self.send(APP_ROOT+'_routes_url')
	end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_layout
			if params['layout']
				@layout = params['layout']
			else
      	@layout = APP_ROOT
			end
    end

    # Only allow a trusted parameter "white list" through.
    def single_page_params
      params.require(:record).permit(:layout)
    end
end

app/views/single_pages/_many_records.html.erb
<!-- C O N T E N T -->

<% @mr.each_with_index do |record, idx| %>
	<h2><%= record[:record_name].pluralize %></h2>
	<table-of-records
		:ref='refName(<%= idx %>)'
		record-name='<%= record[:record_name] %>'
		table-name='<%= record[:table_name] %>'
		v-bind:default-amount-per-page='7'
		v-bind:column-names='<%= raw record[:attr_names] %>'
		v-bind:column-types='<%= raw record[:attr_types].to_json %>'
		v-bind:column-defaults='<%= raw record[:defaults].to_json %>'
		v-bind:column-nulls='<%= raw record[:nulls].to_json %>'
		@table-mounted='tableMounted($event)'
		@api-trigger='apiTrigger($event)'
	>
	</table-of-records>
	<%= link_to "Here", records_path(record[:table_name]) %>
<% end %>
<br/> <!-- this is important! -->

<ul id='notice'>
	<li v-for='(item, idx) in henry.logItems' :key='idx' v-if='item.active'>
		<a class="pseudo button" href="#delete" @click='item.active = false'>x</a><span :class='item.class' v-html="item.message">
	</li>
</ul>

<label>
	<input type="checkbox" v-model="henry.logToConsole">
	<span class="checkable">Log to coleslaw?</span>
</label>

app/views/single_pages/_record.html.erb
<div class='app-entrypoint'>
	
	<h2><%= @record_name.pluralize %></h2>

	<table-of-records
		ref='T'
		record-name='<%= @record_name %>'
		table-name='<%= @table_name %>'
		v-bind:writeable='<%= @writeable.nil? ? true : @writeable %>'
		v-bind:default-amount-per-page='25'
		v-bind:column-names='<%= raw @record_attr_names %>'
		v-bind:column-types='<%= raw @record_attr_types.to_json %>'
		v-bind:column-defaults='<%= raw @record_defaults.to_json %>'
		v-bind:column-nulls='<%= raw @record_nulls.to_json %>'
		@table-mounted='tableMounted($event)'
		@api-trigger='apiTrigger($event)'
	>
	</table-of-records>

	<br/> <!-- this is important! -->

	<p>
	Notice goes here
	</p>


</div>

app/views/single_pages/_the_home.html.erb
<div>Home is where the heart is.</div>

app/views/single_pages/catalogue.html.erb
<style>
.directory > section {
  text-align: left;
  max-width: 960px;
  margin: 0 auto;
}

.tab-item > img {
	opacity: 0.4;
}
</style>

<!-- everything is code :/ -->
<code>
	<main class="directory">
		<section class="flex two">
			<div class="full">
				<h1>Emerging Philosophy</h1>
			</div>
			<aside class="fourth">
				<h2>something</h2>
				<h2>someone</h2>
				<h2>somewhere</h2>
				<h2>sometime</h2>
				<h2>somehow</h2>
			</aside>
			<article class="three-fourth">
				<p>
				Digital transformation is creating many emerging fields. Each of these
				fields has its own field of study. Sometimes these fields are so novel
				that it becomes interesting to track these fields and their attendant
				field of study and to record the information in one location. The intersection
				of computing and philosophy is just such a field. <em>Emerging Philosophy</em>
				is just such a location. <em>Emerging Philosophy</em> is unashamedly
				modelled on the <a href="https://elmcip.net/knowledgebase">eLMcip Knowledge Base</a> . Indeed, we have been in contact
				with a view to leverage common data models.
				</p>
				<div class="tabs three">
					<input id='tab-1' type='radio' name='tabgroupB' checked />
					<label class="pseudo button toggle" for="tab-1">Entities</label>
					<input id='tab-2' type='radio' name='tabgroupB'>
					<label class="pseudo button toggle" for="tab-2">Types</label>
					<input id='tab-3' type='radio' name='tabgroupB'>
					<label class="pseudo button toggle" for="tab-3">?</label>
					<div class="row">
						<div class="tab-item">
							<img src="images/abstract-architecture-attractive-988873.jpg">
							<!-- the catalogue root element -->
							<div id="entities">
								<ul-node :a_model="entityData">
								</ul>
								<transition name="fade">
									<div class="error" v-if="hasError" v-html="error"></div>
								</transition>
							</div>
						</div>

						<div class="tab-item">
							<img src="images/cracks-design-exterior-941552.jpg">
						</div>

						<div class="tab-item">
							<img src="images/abstract-angle-architecture-1005644.jpg">
						</div>
					</div>
				</div>
			</article>
		</section>
	</main>
</code>

<!--
	TODO: package axios and picnic up so that it all gets bundled into one file
				picnic is loaded in the head
-->
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<%= javascript_pack_tag 'entities_vue' %>

app/views/single_pages/li.html.erb
<style>
	body {
		font-family: Menlo, Consolas, monospace;
		color: #444;
	}
	.a_node {
		cursor: pointer;
	}
	.bold {
		font-weight: bold;
	}
	/*ul {
		padding-left: 1em;
		line-height: 1.5em;
		list-style-type: dot;
	}*/
	ul.tree, ul.tree ul {
    list-style: none;
    margin: 0;
    padding: 0;
  }
  ul.tree ul {
    margin-left: 10px;
  }
  ul.tree li {
    margin: 0;
    padding: 0 7px;
    line-height: 20px;
    color: #369;
    /* font-weight: bold; */
    border-left:1px solid rgb(100,100,100);
	}
  ul.tree li:last-child {
    border-left:none;
  }
  ul.tree li:before {
    position:relative;
    top:-0.3em;
    height:1em;
    width:12px;
    color:white;
    border-bottom:1px solid rgb(100,100,100);
    content:"";
    display:inline-block;
    left:-7px;
  }
  ul.tree li:last-child:before {
    border-left:1px solid rgb(100,100,100);
  }
	li .actions {
		display: none;
		color: #cc9a9a;
		transition: color 0.2s ease-out;
	}
	li .actions:hover {
		color: #af5b5e;
	}
	/* https://stackoverflow.com/questions/29210850/how-to-hover-on-child-li-elements */
	li span:hover .actions {
		display: inline;
	}
	span .remove-node:after {
		content: '×';
	}
	span .make-folder:after {
		content: '*';
	}
	.error {
		color: #af5b5e;
	}
	.fade-enter-active, .fade-leave-active {
  	transition: opacity .5s;
	}
	.fade-enter, .fade-leave-to /* .fade-leave-active below version 2.1.8 */ {
  	opacity: 0;
	}
</style>

<!-- node template -->
<script type="text/x-template" id="li-node-template">
	<li v-if="!removed">
		<!-- hasChildren is computed, open is boolean data -->
    <span :class="{bold: hasChildren}" :node-id="n_model.id">
			<span contenteditable @keydown.enter.prevent="updateLiNode(this, $event)" v-text="content"></span>
			<span @click="toggleOpenClose" v-if="hasChildren">{{ open ? '🗁' : '🗀' }}</span>
			<span class="actions">
				<span class="remove-node" @click="removeNode"></span>
				<span class="make-folder" @click="makeFolder"></span>
			</span>
    </span>
		<ul v-show="open" v-if="hasChildren"> 
      <li-node
        class="a_node"
        v-for="(child, index) in n_model.children"
        :key="index"
        :n_model="child">
			</li-node>
			<li><span>–––––</span></li>
			<li class="add-sibling" @dblclick="addSibling" v-if="allowSiblings">+</li>
    </ul>
	</li>
</script>

<p>(You can double click on a node to turn it into a folder with a child.)</p>
<p>(You can double click on a '+' to create a sibling node.)</p>

<!-- the demo root element -->
<div id="demo">
	<ul class="tree">
  	<li-node class="a_node" :n_model="treeData">
		</li-node>
	</ul>
	<transition name="fade">
		<div class="error" v-if="hasError" v-html="error"></div>
	</transition>
</div>

<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script>
	function init_d3(dummy) {
		console.log('dummy init()')
	}
</script>
<%= javascript_pack_tag 'trees' %>